import Head from 'next/head'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <base href="/haha8" target="_blank"></base>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sample static site deployment
        </h1>

        <p className={styles.description}>
          Get started by editing
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="./page1" target="_self" className={styles.card}>
            <h2>Sample page 1 &rarr;</h2>
            <p>Go to Sample page 1</p>
          </a>

          <a href="./pages/page2" target="_self" className={styles.card}>
            <h2>Sample nested page 2 &rarr;</h2>
            <p>Go to Sample nested page 2</p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Next.js documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://github.com/commitdev/zero" target="_blank">
          Powered by {'Zero'}
        </a>
      </footer>
    </div>
  )
}
